pipeline {
  agent any

  tools {
    maven 'MAVEN_HOME'
    jdk 'JAVA_HOME'
  }

  environment {
    DEPLOY_SERVER = "http://15.207.87.167:8080/"
    CONTEXT_PATH  = "myapp"
  }

  stages {
    stage('Checkout') {
      steps {
        // If repo is private, add credentialsId: 'github-creds' to this git step
        git branch: 'main', url: 'https://github.com/RajaBorusu/DEVOPS-project-with-GIT-MAVEN-JENKINS-TOMCAT.git'
      }
    }

    stage('Build') {
      steps {
        sh 'mvn -B clean package'   // -B for non-interactive
      }
    }

    
    stage('Deploy to Tomcat') {
      steps {
        // Uses credentials stored in Jenkins with ID 'tomcat-cred'
        deploy adapters: [
          tomcat8(credentialsId: 'tomcat-cred', path: '', url: "${DEPLOY_SERVER}")
        ], contextPath: "${CONTEXT_PATH}", war: '**/target/*.war'
      }
    }
  }

  post {
    success { echo '✅ SUCCESS: Build and deploy finished.' }
    failure { echo '❌ FAILURE: Check console output.' }
  }
}
