DEVOPS END-END Real Time project with GIT,MAVEN & TOMCAT ||



present pipeline


pipeline {
  agent any

  tools {
    maven 'MAVEN_HOME'
    jdk 'JAVA_HOME'
  }

  environment {
    DEPLOY_SERVER = "http://13.127.104.237:8080/"
    CONTEXT_PATH  = "newappp"
  }

  stages {
    stage('Git Checkout') {
      steps {
                git branch: 'main', url: 'https://github.com/RajaBorusu/DEVOPS-project-with-GIT-MAVEN-JENKINS-TOMCAT.git'
      }
    }

    stage('Build') {
      steps {
        sh 'mvn -B clean package'   // -B for non-interactive
      }
    }

    
    stage('Deploy to Tomcat') {
      steps {
        // we use credentials stored in Jenkins with ID 'tomcat-cred'
        deploy adapters: [
          tomcat8(credentialsId: 'tomcat-cred', path: '', url: "${DEPLOY_SERVER}")
        ], contextPath: "${CONTEXT_PATH}", war: '**/target/*.war'
      }
    }
  }

  post {
    success { echo '✅ SUCCESS: Build and deploy finished.' }
    failure { echo '❌ FAILURE: Check console output.' }
  }
}
